### ISSUE TITLE
Code for H2 ADC 0 and 1?

### ISSUE THREAD

**Issue by bigdady70** [ROHMUSDC/ROHM_SensorPlatform_Multi-Sensor-Shield#10]
All,
If this is the improper forum for a question, please direct me appropriately.

I am using the Multitech dragonfly with this shield. How do I read H2 ADC[0] and ADC[1] which I have wired to analog sensors? How are these pins addressed in code?
Thanks

**Comment by kbahar** [comment]
Hi bigdady70, 

_>>How do I read H2 ADC[0] and ADC[1] which I have wired to analog sensors?_ 
Please see the mbed section on how to use Analog input.
https://developer.mbed.org/handbook/AnalogIn. There are some examples shown in the platform code for the UV sensor.

_>>How are these pins addressed in code?_
I found the following link helpful for the dragonfly pinouts.
https://developer.mbed.org/platforms/MTS-Dragonfly/#pinout-diagram
A0 on Dragonfly is connected to Pin 18 (PC_2)
A1 on Dragonfly is connected to Pin 20 (PC_0)

Best regards,
Kris

**Comment by bigdady70** [comment]
Kris,
A follow up question please, as this is my first time wiring up something external to the dragonfly with the Rohm Expansion Board.

On H2 of the Rohm Expansion / Sensor Board, the Rohm Schematic diagram (page 3 of https://github.com/ROHMUSDC/ROHM_SensorPlatform_Multi-Sensor-Shield/blob/master/Documentation/Sensor%20Shield%20HW%20PDF%20Files/ROHM_SENSORSHLD1-EVK-101_BRD_REV01_2016-03-24.pdf ), labels ADC [0] and ADC[1]. And reading your response, above, is the below correct?
ADC[0] = A0 which is connected to Pin 18 (PC_2) and
ADC[1] = A1 which is connected to Pin 20 (PC_0) ?

If the above is correct, then I believe I understand the situation. The different Headers (Hx where x is a number corresponding to a Header in the schematic) are all connected to the same A/D converter. The expansion headers allow more analog inputs based on the size of the header, but they all trace back to the same A/D converter. Correct?

Thank you again for your patience and guidance.
Brian

**Comment by kbahar** [comment]
Hi Brian,

I would recommend you take a look at the schematic file at the following link:
https://github.com/ROHMUSDC/ROHM_SensorPlatform_Multi-Sensor-Shield/blob/master/Documentation/Sensor%20Shield%20HW%20PDF%20Files/ROHM_SENSORSHLD1-EVK-101_SCH_REV01_2016-03-16.pdf

The board file you referenced works but as it is a PDF file, it is difficult to see where the pins are routed to in that file.  In the schematic shown above, we can see that the H2 ADC pins are routed to A0 and A1.  See below for some snipped images from the schematic:
![image](https://cloud.githubusercontent.com/assets/7607426/16468349/54619192-3e00-11e6-8b91-4bf8e6ac24ff.png)
![image](https://cloud.githubusercontent.com/assets/7607426/16468361/6791d9e8-3e00-11e6-8cc0-916c599dba4f.png)
Therefore, it looks like your indications are correct:
_ADC[0] = A0 which is connected to Pin 18 (PC_2)
ADC[1] = A1 which is connected to Pin 20 (PC_0)_

_>>The different Headers (Hx where x is a number corresponding to a Header in the schematic) are all connected to the same A/D converter. The expansion headers allow more analog inputs based on the size of the header, but they all trace back to the same A/D converter. Correct?_
The above is partially correct; the different headers were built in to accommodate any extra sensor devices users may want to add to the device, however they are not all connected to the same A/D converter.  These points are all connected to different pins on the shield board, which then get routed to different pins on the host board (in this case, the host board is the multitech dragonfly). As long as the pins connected to the host board support A/D conversion, it should work correctly.

BR,
Kris
