### ISSUE TITLE
 I2C Init Failed (SDA or SCL may not be pulled up!

### ISSUE THREAD

**Issue by OdingdongO** [ROHMUSDC/ROHM_SensorPlatform_Multi-Sensor-Shield#11]
When I use the demo "ROHM_SENSORSHLD1-EVK-101_TerminalDemo_11-10-2016.ino",the error is printed in the serial port. "I2C Init Failed (SDA or SCL may not be pulled up!"

**Comment by kbahar** [comment]
See Question 4 in the FAQ section of the readme for this repository.
